export enum AksesMenuButtonEnum {
  RUANG_PENSIUN = 'RUANG-PENSIUN',
  ASTRAHUB = 'ASTRAHUB',
  EKLAIM = 'EKLAIM',
  LAPORAN_INVESTASI = 'LAPORAN-INVESTASI',
  SIMULASI_MANFAAT_PENSIUN = 'SIMULASI-MANFAAT-PENSIUN',
  BACA = 'BACA',
  QUIZ = 'QUIZ',
  PROMOSI = 'PROMOSI',
  JOBS = 'JOBS',
}
